### ISSUE TITLE
Maven dependency ?

### ISSUE THREAD

**Issue by keplerk** [EsotericSoftware/tablelayout#15]
Is this available on maven or do i have to compile it myself? i need to make a java 1.8 project and this will for sure helps a lot !

**Comment by NathanSweet** [comment]
It's not in a Maven repo AFAIK. I don't do Swing, Android, or TWL UI anymore so I haven't used it in a long time. It's most widely used as part of libgdx, which contains a fork:
https://github.com/libgdx/libgdx/wiki/Table/6a41dee25380a8dcd0f3ed9263267684c55ba6ab

**Comment by keplerk** [comment]
Thanks, still i just download the master and compile it myself, installed it on my local m2 folder and it's done  😁
