### ISSUE TITLE
AndroidToolkit.context

### ISSUE THREAD

**Issue by mgood7123** [EsotericSoftware/tablelayout#9]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.BroadcastConsole, PID: 16947
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.BroadcastConsole/com.example.broadcastConsole.grid.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3108)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3251)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7045)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
        at android.view.ViewConfiguration.get(ViewConfiguration.java:476)
        at android.view.View.<init>(View.java:5198)
        at android.view.View.<init>(View.java:5393)
        at android.view.ViewGroup.<init>(ViewGroup.java:660)
        at android.view.ViewGroup.<init>(ViewGroup.java:656)
        at android.view.ViewGroup.<init>(ViewGroup.java:652)
        at android.view.ViewGroup.<init>(ViewGroup.java:648)
        at com.esotericsoftware.tablelayout.Table.<init>(Table.java:35)
        at com.esotericsoftware.tablelayout.Table.<init>(Table.java:31)
        at com.example.broadcastConsole.grid.MainActivity.onCreate(MainActivity.kt:36)
        at android.app.Activity.performCreate(Activity.java:7327)
        at android.app.Activity.performCreate(Activity.java:7318)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3088)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3251) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7045) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964) 
Application terminated.

```        // Keep your code clean by creating widgets separate from layout.

        val textView = TextView(applicationContext)
        textView.text = "a".toString()
        textView.setTextColor(Color.WHITE)
        textView.setAutoSizeTextTypeWithDefaults(TextView.AUTO_SIZE_TEXT_TYPE_UNIFORM)
        textView.setPadding(0, 0, 0, 0)
        textView.setTypeface(Typeface.MONOSPACE, Typeface.BOLD)
        val table = Table()```

**Comment by NathanSweet** [comment]
Stacktrace shows:
```
at com.esotericsoftware.tablelayout.Table.(Table.java:35)
```
That [package](https://github.com/EsotericSoftware/tablelayout/tree/master/tablelayout/src/com/esotericsoftware/tablelayout) doesn't have a class named Table. For Android the class is [com.esotericsoftware.tablelayout.android.Table](https://github.com/EsotericSoftware/tablelayout/blob/master/tablelayout-android/src/com/esotericsoftware/tablelayout/android/Table.java#L35) and line 35 is blank.

**Comment by mgood7123** [comment]
> Stacktrace shows:
> 
> ```
> at com.esotericsoftware.tablelayout.Table.(Table.java:35)
> ```
> 
> That [package](https://github.com/EsotericSoftware/tablelayout/tree/master/tablelayout/src/com/esotericsoftware/tablelayout) doesn't have a class named Table. For Android the class is [com.esotericsoftware.tablelayout.android.Table](https://github.com/EsotericSoftware/tablelayout/blob/master/tablelayout-android/src/com/esotericsoftware/tablelayout/android/Table.java#L35) and line 35 is blank.

line 35 is `		super(AndroidToolkit.context);
`


(had to put all files in a single folder cus IntelliJ wouldnt correctly import it)
```

package com.esotericsoftware.tablelayout;

import android.graphics.Canvas;
import android.view.View;
import android.view.ViewGroup;

import com.esotericsoftware.tablelayout.BaseTableLayout.Debug;

import java.util.List;

public class Table extends ViewGroup {
	static {
		Toolkit.instance = new AndroidToolkit();
	}

	static private final OnHierarchyChangeListener hierarchyChangeListener = new OnHierarchyChangeListener() {
		public void onChildViewAdded (View parent, View child) {
			((Table)parent).layout.otherChildren.add(child);
		}

		public void onChildViewRemoved (View parent, View child) {
			((Table)parent).layout.otherChildren.remove(child);
		}
	};

	final TableLayout layout;
	private boolean sizeToBackground;

	public Table () {
		this(new TableLayout());
	}

	public Table (TableLayout layout) {
		super(AndroidToolkit.context);
		this.layout = layout;
		layout.setTable(this);
		setLayoutParams(new LayoutParams(LayoutParams.FILL_PARENT, LayoutParams.FILL_PARENT));
		setOnHierarchyChangeListener(hierarchyChangeListener);
	}

	public Cell add (View view) {
		return layout.add(view);
	}

	public Cell row () {
		return layout.row();
	}

	public Cell columnDefaults (int column) {
		return layout.columnDefaults(column);
	}

	public Cell defaults () {
		return layout.defaults();
	}

	protected void onMeasure (int widthMeasureSpec, int heightMeasureSpec) {
		boolean widthUnspecified = MeasureSpec.getMode(widthMeasureSpec) == MeasureSpec.UNSPECIFIED;
		boolean heightUnspecified = MeasureSpec.getMode(heightMeasureSpec) == MeasureSpec.UNSPECIFIED;

		measureChildren(MeasureSpec.makeMeasureSpec(0, MeasureSpec.UNSPECIFIED),
			MeasureSpec.makeMeasureSpec(0, MeasureSpec.UNSPECIFIED));

		// Measure GONE children to 0x0.
		List<Cell> cells = layout.getCells();
		for (int i = 0, n = cells.size(); i < n; i++) {
			Cell c = cells.get(i);
			if (c.getIgnore()) continue;
			if (((View)c.getWidget()).getVisibility() == GONE) {
				((View)c.getWidget()).measure(MeasureSpec.makeMeasureSpec(0, MeasureSpec.EXACTLY),
					MeasureSpec.makeMeasureSpec(0, MeasureSpec.EXACTLY));
			}
		}

		layout.layout(0, 0, //
			widthUnspecified ? 0 : MeasureSpec.getSize(widthMeasureSpec), //
			heightUnspecified ? 0 : MeasureSpec.getSize(heightMeasureSpec));

		int measuredWidth = (int)(widthUnspecified ? layout.getMinWidth() : layout.getPrefWidth());
		int measuredHeight = (int)(heightUnspecified ? layout.getMinHeight() : layout.getPrefHeight());

		invalidate();
		measuredWidth = Math.max(measuredWidth, getSuggestedMinimumWidth());
		measuredHeight = Math.max(measuredHeight, getSuggestedMinimumHeight());

		setMeasuredDimension(resolveSize(measuredWidth, widthMeasureSpec), resolveSize(measuredHeight, heightMeasureSpec));
	}

	protected void onLayout (boolean changed, int left, int top, int right, int bottom) {
		layout.layout(0, 0, right - left, bottom - top);

		if (layout.getDebug() != Debug.none && layout.debugRects != null) {
			setWillNotDraw(false);
			invalidate();
		}
	}

	public void requestLayout () {
		if (layout != null) layout.invalidateSuper();
		super.requestLayout();
	}

	protected int getSuggestedMinimumWidth () {
		int width = (int)layout.getMinWidth();
		if (sizeToBackground && getBackground() != null) width = Math.max(width, getBackground().getMinimumWidth());
		return width;
	}

	protected int getSuggestedMinimumHeight () {
		int height = (int)layout.getMinHeight();
		if (sizeToBackground && getBackground() != null) height = Math.max(height, getBackground().getMinimumHeight());
		return height;
	}

	protected void dispatchDraw (Canvas canvas) {
		super.dispatchDraw(canvas);
		layout.drawDebug(canvas);
	}

	public void setSizeToBackground (boolean sizeToBackground) {
		this.sizeToBackground = sizeToBackground;
	}

	public TableLayout getTableLayout () {
		return layout;
	}
}

```

**Comment by NathanSweet** [comment]
Ah, ok. Likely you need to set `AndroidToolkit.context` to your application context before creating Table instances. Sorry there are no Android examples.

**Comment by mgood7123** [comment]
`Type mismatch: inferred type is android.widget.TableLayout but com.esotericsoftware.tablelayout.android.TableLayout! was expected	`

```
        val l = TableLayout(applicationContext)
        val table = Table(l)
```

**Comment by mgood7123** [comment]
could you modify

```
public Table () {
		this(new TableLayout());
	}
```

such that it accepts an Context paramater which gets passed to
```
	public Table (TableLayout layout) {
		super(AndroidToolkit.context);
```

**Comment by NathanSweet** [comment]
All you need is the following code when your app starts, before you create any tables:
```
AndroidToolkit.context = applicationContext;
```

**Comment by mgood7123** [comment]
ok, could you add that to the example lol

**Comment by mgood7123** [comment]
Cannot access 'AndroidToolkit': it is public/*package*/ in 'com.esotericsoftware.tablelayout.android'	

`        com.esotericsoftware.tablelayout.android.AndroidToolkit.context = applicationContext`

**Comment by mgood7123** [comment]
```
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
```

**Comment by NathanSweet** [comment]
Sorry again, I use TableLayout with libgdx every day, but I haven't used it with Android for years. I did build an entire app with it, but I can't seem to find that source code!

Instead of setting `AndroidToolkit.context` you should call `setup`:
```
AndroidToolkit.setup(yourActivity, R.drawable.class);
```
I've made `AndroidToolkit` public.

For Android, `Table` is an android.view.ViewGroup. To manipulate the layout, like to set debug, you'll need to do so on the `TableLayout`:
```
Table table = new Table();
table.getTableLayout().debug();
```

I'll add a section to the docs for this kind of Android-specific stuff.

**Comment by mgood7123** [comment]
```
	public void debug() {
		layout.debug();
	}
	public void debugTable() {
		layout.debugTable();
	}
```
to make it `debug()` and `debugTable()` callable from kotlin, since attempting to access `table.tableLayout // from getTableLayout()`

produces Cannot access 'TableLayout': it is public/*package*/ in 'com.esotericsoftware.tablelayout.android'

```
public TableLayout getTableLayout () {
		return layout;
	}
```

**Comment by mgood7123** [comment]
OR

```
com/esotericsoftware/tablelayout/android/Table.java : 29
final TableLayout layout; -> public final TableLayout layout;

com/esotericsoftware/tablelayout/android/TableLayout.java : 16
class TableLayout extends BaseTableLayout<View, Table, TableLayout, AndroidToolkit> {
->
public class TableLayout extends BaseTableLayout<View, Table, TableLayout, AndroidToolkit> {
```

**Comment by NathanSweet** [comment]
Hmm, some of the BaseTableLayout methods are passed through from Table to the layout, but not all. There are many BaseTableLayout methods: `padBottom`, `getPadBottom`, etc. I guess it's fine for Table to have them all, since it makes using the Table API more pleasant. Would you like to submit a PR to add them all?

TableLayout can remain package private, as it is the Android-specific implementation of BaseTableLayout and doesn't expose anything additional. `getTableLayout` should just return BaseTableLayout. I've made that change.

**Comment by mgood7123** [comment]
ill try to

**Comment by mgood7123** [comment]
ummm what functions SHOULD be callable and what functions should NOT be callable

**Comment by NathanSweet** [comment]
Most of the public methods. No worries, I'll add the methods, one moment please!

**Comment by NathanSweet** [comment]
Alright, I added delegate methods, copying the comments from BaseTableLayout (compiled but untested, what could go wrong). The only one that conflicted with the ViewGroup methods is `invalidate`. It wasn't clear if we want to invalidate the layout when View#invalidate is called, so I left the delegate method commented. We do for Swing but who knows for Android, would need to try it and see when invalidate is called. FWIW, ViewGroup#invalidate didn't invalidate the layout previously and it was working then.

**Comment by mgood7123** [comment]
ok

**Comment by NathanSweet** [comment]
Will close this issue but feel free to post here if you find things aren't working right. Cheers!
